language: java
sudo: required
jdk:
  - oraclejdk8

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y rpm

services:
  - mysql
  - postgres

before_script:
  - cp -vf liquibase-integration-tests/src/test/resources/liquibase/liquibase.integrationtest.circleci.properties liquibase-integration-tests/src/test/resources/liquibase/liquibase.integrationtest.local.properties
  - mvn compile -B
  - mkdir -p /home/travis/ts_liquibase2
  - sudo chown postgres.postgres /home/travis/ts_liquibase2
  - psql postgres -f liquibase-integration-tests/setup/postgresql/create_dbs_for_integration_tests.sql --variable="path_for_tablespace='/home/travis/ts_liquibase2'"
  - mysql --verbose -u root mysql < liquibase-integration-tests/setup/mysql/create_dbs_for_integration_tests.sql

script: mvn install -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
