language: java
sudo: required
jdk:
  - oraclejdk8

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y rpm

services:
  - mysql

before_script:
  - mysql -uroot < liquibase-integration-tests/src/test/resources/travis-ci/mysql-setup.sql

script: mvn clean verify
