language: java

jdk: openjdk8

install: true

script: mvn package -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

cache:
  directories:
  - ~/.m2

addons:
  apt:
    packages:
    - rpm  