language: java
sudo: required
jdk:
  - openjdk6

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y rpm

script: mvn clean package

test:
  post:
    - mkdir -p $CIRCLE_TEST_REPORTS/junit/
    - find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} $CIRCLE_TEST_REPORTS/junit/ \;
    - cp liquibase-core/target/liquibase*-bin.zip $CIRCLE_ARTIFACTS
    - cp liquibase-core/target/liquibase*-bin.tar.gz $CIRCLE_ARTIFACTS
    - cp liquibase-core/target/liquibase*-SNAPSHOT.jar $CIRCLE_ARTIFACTS
    - cp liquibase-rpm/target/*.rpm $CIRCLE_ARTIFACTS
    - cp liquibase-debian/target/*.deb $CIRCLE_ARTIFACTS